# Generated by Django 4.0.4 on 2022-04-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justSaid_web', '0013_profile_facebook_url_profile_instagarm_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagarm_url',
            new_name='instagram_url',
        ),
    ]
