# Generated by Django 4.0.4 on 2022-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justSaid_web', '0014_rename_instagarm_url_profile_instagram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='instragram_url',
        ),
    ]
